import React, { createContext, useState, type ReactNode } from 'react';
import { AuthContext } from './AuthContext';
import axiosInstance from '../api/axiosInstance';

export interface Currency {
  code: string;
  symbol: string;
  locale: string;
  name: string;
  flag: string;
  lang: 'id' | 'en' | 'ja' | 'ms';
}

export const currencies: Currency[] = [
  { code: 'IDR', symbol: 'Rp', locale: 'id-ID', name: 'Rupiah', flag: '🇮🇩', lang: 'id' },
  { code: 'USD', symbol: '$', locale: 'en-US', name: 'US Dollar', flag: '🇺🇸', lang: 'en' },
  { code: 'EUR', symbol: '€', locale: 'en-IE', name: 'Euro', flag: '🇪🇺', lang: 'en' },
  { code: 'JPY', symbol: '¥', locale: 'ja-JP', name: 'Yen', flag: '🇯🇵', lang: 'ja' },
  { code: 'GBP', symbol: '£', locale: 'en-GB', name: 'Pound', flag: '🇬🇧', lang: 'en' },
  { code: 'SGD', symbol: 'S$', locale: 'en-SG', name: 'Singapore Dollar', flag: '🇸🇬', lang: 'en' },
  { code: 'MYR', symbol: 'RM', locale: 'ms-MY', name: 'Ringgit', flag: '🇲🇾', lang: 'ms' },
];

// Translation dictionary
export type TranslationKey =
  | 'dashboard' | 'income' | 'expense' | 'contact' | 'daily_journal'
  | 'total_income' | 'total_expense' | 'net_profit' | 'gross_profit'
  | 'financial_report' | 'finance' | 'welcome_tagline'
  | 'all_totals' | 'income_ytd' | 'expense_ytd'
  | 'revenue_expense_12m' | 'revenue' | 'operating_margin'
  | 'gross_profit_12m' | 'gross_profit_line' | 'gross_margin'
  | 'income_expense_comparison' | 'expense_by_category'
  | 'loading_dashboard' | 'ai_help' | 'logout'
  | 'food' | 'beauty' | 'culture' | 'health' | 'gift'
  | 'transportation' | 'education' | 'household' | 'apparel'
  | 'monthly_income' | 'monthly_expense' | 'net_balance'
  | 'journal_subtitle' | 'calendar_prev' | 'calendar_next'
  | 'income_subtitle' | 'add_income' | 'total_transactions'
  | 'search_income' | 'transaction_date' | 'category'
  | 'description' | 'amount' | 'no_income_data'
  | 'expense_subtitle' | 'add_expense' | 'search_expense' | 'no_expense_data'
  | 'contact_subtitle' | 'add_contact' | 'total_contacts'
  | 'search_contact' | 'contact_name' | 'contact_info'
  | 'address' | 'no_contact_data' | 'actions'
  | 'month_word' | 'surplus' | 'deficit' | 'selected'
  | 'today_balance' | 'no_transactions_today' | 'select_date' | 'click_date_hint'
  | 'at_allfinance' | 'edit_profile' | 'select_category' | 'eg_amount'
  | 'eg_desc_income' | 'eg_desc_expense' | 'cancel'
  | 'financial_target_title' | 'create_target' | 'expense_limit'
  | 'income_savings_target' | 'no_expense_target' | 'no_income_target'
  | 'target_name' | 'eg_target_name' | 'target_type' | 'target_amount'
  | 'period' | '1_day' | '3_days' | '1_week' | '1_month'
  | 'saving' | 'save_target' | 'over_limit' | 'over_limit_desc' | 'ok'
  | 'congrats' | 'target_achieved' | 'continue_btn'
  | 'send_report' | 'report_subject' | 'report_subject_placeholder'
  | 'report_message' | 'report_message_placeholder' | 'sending'
  | 'anti_spam_warning' | 'anti_spam_rule_1' | 'anti_spam_rule_2' | 'anti_spam_rule_3'
  | 'more_options' | 'feature_coming_soon' | 'dashboard_name_updated' | 'dashboard_name_update_failed'
  | 'failed_load_dashboard' | 'fill_target_form' | 'target_saved' | 'target_save_failed'
  | 'confirm_delete_target' | 'target_deleted' | 'target_delete_failed'
  | 'delete_income' | 'delete_expense' | 'security_password_prompt' | 'account_password'
  | 'confirm_delete' | 'income_added_success' | 'income_added_failed'
  | 'income_deleted_success' | 'income_deleted_failed' | 'expense_added_success'
  | 'expense_added_failed' | 'expense_deleted_success' | 'expense_deleted_failed'
  | 'failed_load_data' | 'receipt_photo_optional' | 'fill_report_form' | 'report_sent_success'
  | 'report_sent_failed' | 'notifications_cleared' | 'notifications_clear_failed'
  | 'logout_success' | 'uploading_photo' | 'photo_uploaded_success' | 'photo_upload_failed'
  | 'confirm_clear_notifs' | 'clear_all' | 'no_notifications' | 'notifications'
  | 'admin_load_failed' | 'account_activated' | 'account_suspended' | 'status_update_failed'
  | 'account_deleted' | 'account_delete_failed' | 'receipt_load_failed' | 'reply_empty'
  | 'reply_sent' | 'reply_failed' | 'report_deleted' | 'report_delete_failed'
  | 'delete_account_confirm' | 'delete_report_confirm' | 'account_suspended_title'
  | 'account_suspended_desc' | 'report_to_admin' | 'delete_profile_picture'
  | 'delete_receipt_photo' | 'profile_picture_deleted' | 'profile_picture_delete_failed'
  | 'receipt_photo_deleted' | 'receipt_photo_delete_failed' | 'confirm_delete_profile_picture'
  | 'confirm_delete_receipt_photo'
  | 'receipt' | 'new_expense_recorded' | 'new_income_recorded'
  | 'label_used' | 'label_limit' | 'label_collected' | 'label_target' | 'label_time_left' | 'label_until' | 'currency';

export type Translations = Record<TranslationKey, string>;

const translations: Record<'id' | 'en' | 'ja' | 'ms', Translations> = {
  id: {
    dashboard: 'Halaman Utama',
    income: 'Pemasukan',
    expense: 'Pengeluaran',
    contact: 'Kontak',
    daily_journal: 'Kalender Daily',
    total_income: 'Total Pendapatan',
    total_expense: 'Total Pengeluaran',
    net_profit: 'Sisa Saldo / Uang Tersisa',
    gross_profit: 'Laba Kotor',
    financial_report: 'Laporan',
    finance: 'Keuangan',
    welcome_tagline: 'Selamat datang di AllFinance, Aplikasi platfrom manajemen keuangan pintar Anda. Pantau catatan pemasukan dan pengeluaran anda dengan lebih mudah.',
    all_totals: 'Semua Total Perhitungan',
    income_ytd: 'Pendapatan (YTD)',
    expense_ytd: 'Pengeluaran (YTD)',
    revenue_expense_12m: 'Pendapatan Operasional dan Pengeluaran (12 bulan terakhir)',
    revenue: 'Pendapatan',
    operating_margin: 'Margin Operasional',
    gross_profit_12m: 'Laba Kotor 12 Bulan Terakhir',
    gross_profit_line: 'Laba Kotor',
    gross_margin: 'Margin Kotor',
    income_expense_comparison: 'Perbandingan Pemasukan & Pengeluaran',
    expense_by_category: 'Pengeluaran per Kategori',
    loading_dashboard: 'Memuat Dasbor...',
    ai_help: 'Bantuan AI',
    logout: 'Keluar',
    food: 'Makanan',
    beauty: 'Kecantikan',
    culture: 'Budaya',
    health: 'Kesehatan',
    gift: 'Hadiah',
    transportation: 'Transportasi',
    education: 'Pendidikan',
    household: 'Rumah Tangga',
    apparel: 'Pakaian',
    monthly_income: 'Total Pemasukan Bulan Ini',
    monthly_expense: 'Total Pengeluaran Bulan Ini',
    net_balance: 'Total Saldo Bersih',
    journal_subtitle: 'Ringkasan transaksi keuangan harian',
    calendar_prev: 'Bulan Sebelumnya',
    calendar_next: 'Bulan Berikutnya',
    income_subtitle: 'Lacak dan kelola sumber pendapatan Anda',
    add_income: 'Tambah Pemasukan',
    total_transactions: 'Total Transaksi',
    search_income: '🔍 Cari pemasukan...',
    transaction_date: 'Tanggal Transaksi',
    category: 'Kategori',
    description: 'Keterangan',
    amount: 'Jumlah',
    no_income_data: 'Belum ada data pemasukan',
    expense_subtitle: 'Lacak dan kelola pengeluaran Anda',
    add_expense: 'Tambah Pengeluaran',
    search_expense: '🔍 Cari pengeluaran...',
    no_expense_data: 'Belum ada data pengeluaran',
    contact_subtitle: 'Kelola kontak dan rekan bisnis Anda',
    add_contact: 'Tambah Kontak',
    total_contacts: 'Total Kontak',
    search_contact: '🔍 Cari kontak...',
    contact_name: 'Nama Kontak',
    contact_info: 'Informasi Kontak',
    address: 'Alamat',
    no_contact_data: 'Belum ada kontak',
    actions: 'Aksi',
    month_word: 'Bulan',
    surplus: 'Surplus',
    deficit: 'Defisit',
    selected: 'Dipilih',
    today_balance: 'Saldo Hari Ini',
    no_transactions_today: 'Tidak ada transaksi hari ini',
    select_date: 'Pilih Tanggal',
    click_date_hint: 'Klik salah satu tanggal di kalender untuk melihat detail transaksi harian Anda',
    at_allfinance: 'di AllFinance',
    edit_profile: 'Ubah Profil Saya',
    select_category: 'Pilih Kategori',
    eg_amount: 'cth. 500.00',
    eg_desc_income: 'cth. Menjual 5 unit Produk X',
    eg_desc_expense: 'cth. Membeli bahan baku',
    cancel: 'Batal',
    financial_target_title: 'TARGET KEUANGAN',
    create_target: 'Buat Target',
    expense_limit: 'Batasan Pengeluaran',
    income_savings_target: 'Target Pemasukan / Tabungan',
    no_expense_target: 'Belum ada target pengeluaran.',
    no_income_target: 'Belum ada target pemasukan.',
    target_name: 'Nama Target',
    eg_target_name: 'Contoh: Belanja Bulanan / Beli Sepatu',
    target_type: 'Jenis Target',
    target_amount: 'Nominal Target',
    period: 'Periode',
    '1_day': '1 Hari',
    '3_days': '3 Hari',
    '1_week': '1 Minggu',
    '1_month': '1 Bulan',
    saving: 'Menyimpan...',
    save_target: 'Simpan Target',
    over_limit: 'Pengeluaran Berlebihan!',
    over_limit_desc: 'Pengeluaran Anda telah mencapai atau melebihi target batasan yang ditentukan. Target ini akan dihapus.',
    ok: 'OK',
    congrats: 'Selamat! 🎉',
    target_achieved: 'Anda telah berhasil mencapai target',
    continue_btn: 'Lanjutkan',
    send_report: 'Kirim Laporan',
    report_subject: 'Subjek',
    report_subject_placeholder: 'Misal: Bug, Fitur Baru, atau Bantuan',
    report_message: 'Pesan Laporan',
    report_message_placeholder: 'Jelaskan masalah atau laporan Anda secara detail...',
    sending: 'Mengirim...',
    anti_spam_warning: 'Peringatan Sistem Anti-Spam:',
    anti_spam_rule_1: 'Anda memiliki batas maksimal 3 kuota laporan.',
    anti_spam_rule_2: 'Jika kuota habis, Anda harus menunggu 2 hari.',
    anti_spam_rule_3: 'Jika melanggar lebih dari 3 kali, akun akan dihapus otomatis!',
    more_options: 'Opsi Lainnya',
    feature_coming_soon: 'Fitur lainnya akan hadir',
    dashboard_name_updated: 'Nama dasbor berhasil diperbarui',
    dashboard_name_update_failed: 'Gagal memperbarui nama dasbor',
    failed_load_dashboard: 'Gagal memuat data dasbor',
    fill_target_form: 'Lengkapi form target',
    target_saved: 'Target berhasil disimpan',
    target_save_failed: 'Gagal menyimpan target',
    confirm_delete_target: 'Apakah Anda yakin ingin menghapus target ini?',
    target_deleted: 'Target berhasil dihapus',
    target_delete_failed: 'Gagal menghapus target',
    label_used: 'Terpakai',
    label_limit: 'Batas',
    label_collected: 'Terkumpul',
    label_target: 'Target',
    label_time_left: 'Sisa Waktu',
    label_until: 's/d',
    delete_income: 'Hapus Pemasukan',
    delete_expense: 'Hapus Pengeluaran',
    security_password_prompt: 'Untuk alasan keamanan, masukkan kata sandi akun Anda untuk mengonfirmasi penghapusan data ini.',
    account_password: 'Kata Sandi Akun',
    confirm_delete: 'Konfirmasi Hapus',
    income_added_success: 'Pemasukan berhasil ditambahkan!',
    income_added_failed: 'Gagal menambahkan pemasukan',
    income_deleted_success: 'Pemasukan berhasil dihapus',
    income_deleted_failed: 'Gagal menghapus pemasukan',
    expense_added_success: 'Pengeluaran berhasil ditambahkan!',
    expense_added_failed: 'Gagal mencatat pengeluaran',
    expense_deleted_success: 'Pengeluaran berhasil dihapus',
    expense_deleted_failed: 'Gagal menghapus pengeluaran',
    failed_load_data: 'Gagal memuat data',
    receipt_photo_optional: 'Foto Kwitansi/Kenangan (Opsional)',
    fill_report_form: 'Harap isi subjek dan pesan laporan',
    report_sent_success: 'Laporan berhasil dikirim ke Admin',
    report_sent_failed: 'Gagal mengirim laporan',
    notifications_cleared: 'Notifikasi dibersihkan',
    notifications_clear_failed: 'Gagal membersihkan notifikasi',
    logout_success: 'Berhasil keluar',
    uploading_photo: 'Mengunggah foto...',
    photo_uploaded_success: 'Foto profil berhasil diperbarui',
    photo_upload_failed: 'Gagal mengunggah foto profil',
    confirm_clear_notifs: 'Bersihkan semua notifikasi?',
    clear_all: 'Bersihkan Semua',
    no_notifications: 'Belum ada notifikasi',
    notifications: 'Notifikasi',
    admin_load_failed: 'Gagal memuat data admin',
    account_activated: 'Akun berhasil diaktifkan',
    account_suspended: 'Akun berhasil ditangguhkan',
    status_update_failed: 'Gagal mengubah status akun',
    account_deleted: 'Akun berhasil dihapus',
    account_delete_failed: 'Gagal menghapus akun',
    receipt_load_failed: 'Gagal memuat kwitansi pengguna',
    reply_empty: 'Teks balasan kosong',
    reply_sent: 'Balasan terkirim',
    reply_failed: 'Gagal mengirim balasan',
    report_deleted: 'Laporan berhasil dihapus',
    report_delete_failed: 'Gagal menghapus laporan',
    delete_account_confirm: 'Yakin ingin menghapus akun ini secara permanen beserta semua transaksinya?',
    delete_report_confirm: 'Yakin ingin menghapus laporan ini?',
    account_suspended_title: 'Akun Ditangguhkan',
    account_suspended_desc: 'Akun Anda telah dikunci oleh administrator karena pelanggaran atau alasan keamanan. Anda tidak dapat melakukan aktivitas apapun di dalam aplikasi.',
    report_to_admin: 'Lapor ke Admin',
    delete_profile_picture: 'Hapus Foto Profil',
    delete_receipt_photo: 'Hapus Foto Kwitansi',
    profile_picture_deleted: 'Foto profil berhasil dihapus',
    profile_picture_delete_failed: 'Gagal menghapus foto profil',
    receipt_photo_deleted: 'Foto kwitansi berhasil dihapus',
    receipt_photo_delete_failed: 'Gagal menghapus foto kwitansi',
    confirm_delete_profile_picture: 'Yakin ingin menghapus foto profil pengguna ini karena tidak pantas?',
    confirm_delete_receipt_photo: 'Yakin ingin menghapus foto kwitansi ini karena tidak pantas?',
    receipt: 'Kwitansi',
    currency: 'Mata Uang',
    new_expense_recorded: 'Pengeluaran baru dicatat',
    new_income_recorded: 'Pemasukan baru ditambahkan',
  },
  en: {
    dashboard: 'Dashboard',
    income: 'Income',
    expense: 'Expenses',
    contact: 'Contacts',
    daily_journal: 'Daily Journal',
    total_income: 'Total Revenue',
    total_expense: 'Total Expenses',
    net_profit: 'Remaining Balance',
    gross_profit: 'Gross Profit',
    financial_report: 'Report',
    finance: 'Finance',
    welcome_tagline: 'Welcome to AllFinance, your smart financial management platform. Monitor and manage your assets with ease.',
    all_totals: 'All Total Calculations',
    income_ytd: 'Revenue (YTD)',
    expense_ytd: 'Expenses (YTD)',
    revenue_expense_12m: 'Operating Revenue and Expenses (last 12 months)',
    revenue: 'Revenue',
    operating_margin: 'Operating Margin',
    gross_profit_12m: 'Gross Profit Last 12 Months',
    gross_profit_line: 'Gross Profit',
    gross_margin: 'Gross Margin',
    income_expense_comparison: 'Income & Expense Comparison',
    expense_by_category: 'Expenses by Category',
    loading_dashboard: 'Loading Dashboard...',
    ai_help: 'AI Help',
    logout: 'Logout',
    food: 'Food',
    beauty: 'Beauty',
    culture: 'Culture',
    health: 'Health',
    gift: 'Gift',
    transportation: 'Transportation',
    education: 'Education',
    household: 'Household',
    apparel: 'Apparel',
    monthly_income: 'Total Income This Month',
    monthly_expense: 'Total Expenses This Month',
    net_balance: 'Total Net Balance',
    journal_subtitle: 'Summary of daily financial transactions',
    calendar_prev: 'Previous Month',
    calendar_next: 'Next Month',
    income_subtitle: 'Track and manage your income sources',
    add_income: 'Add Income',
    total_transactions: 'Total Transactions',
    search_income: '🔍 Search income...',
    transaction_date: 'Transaction Date',
    category: 'Category',
    description: 'Description',
    amount: 'Amount',
    no_income_data: 'No income data yet',
    expense_subtitle: 'Track and manage your expenses',
    add_expense: 'Add Expense',
    search_expense: '🔍 Search expenses...',
    no_expense_data: 'No expense data yet',
    contact_subtitle: 'Manage your contacts and business partners',
    add_contact: 'Add Contact',
    total_contacts: 'Total Contacts',
    search_contact: '🔍 Search contacts...',
    contact_name: 'Contact Name',
    contact_info: 'Contact Info',
    address: 'Address',
    no_contact_data: 'No contacts yet',
    actions: 'Actions',
    month_word: 'Month',
    surplus: 'Surplus',
    deficit: 'Deficit',
    selected: 'Selected',
    today_balance: 'Today\'s Balance',
    no_transactions_today: 'No transactions today',
    select_date: 'Select Date',
    click_date_hint: 'Click a date on the calendar to view daily transaction details',
    at_allfinance: 'at AllFinance',
    edit_profile: 'Edit My Profile',
    select_category: 'Select Category',
    eg_amount: 'e.g. 500.00',
    eg_desc_income: 'e.g. Sold 5 units of Product X',
    eg_desc_expense: 'e.g. Bought raw materials',
    cancel: 'Cancel',
    financial_target_title: 'FINANCIAL TARGET',
    create_target: 'Create Target',
    expense_limit: 'Expense Limit',
    income_savings_target: 'Income / Savings Target',
    no_expense_target: 'No expense targets yet.',
    no_income_target: 'No income targets yet.',
    target_name: 'Target Name',
    eg_target_name: 'e.g., Monthly Groceries / New Shoes',
    target_type: 'Target Type',
    target_amount: 'Target Amount',
    period: 'Period',
    '1_day': '1 Day',
    '3_days': '3 Days',
    '1_week': '1 Week',
    '1_month': '1 Month',
    saving: 'Saving...',
    save_target: 'Save Target',
    over_limit: 'Over Limit!',
    over_limit_desc: 'Your expenses have reached or exceeded the set limit target. This target will be removed.',
    ok: 'OK',
    congrats: 'Congratulations! 🎉',
    target_achieved: 'You have successfully achieved the target',
    continue_btn: 'Continue',
    send_report: 'Send Report',
    report_subject: 'Subject',
    report_subject_placeholder: 'e.g. Bug, New Feature, or Help',
    report_message: 'Report Message',
    report_message_placeholder: 'Explain your issue or report in detail...',
    sending: 'Sending...',
    anti_spam_warning: 'Anti-Spam System Warning:',
    anti_spam_rule_1: 'You have a maximum limit of 3 report quotas.',
    anti_spam_rule_2: 'If the quota is depleted, you must wait 2 days.',
    anti_spam_rule_3: 'If you violate this more than 3 times, your account will be automatically deleted!',
    more_options: 'More Options',
    feature_coming_soon: 'Other features are coming soon',
    dashboard_name_updated: 'Dashboard name updated successfully',
    dashboard_name_update_failed: 'Failed to update dashboard name',
    failed_load_dashboard: 'Failed to load dashboard data',
    fill_target_form: 'Please fill the target form',
    target_saved: 'Target saved successfully',
    target_save_failed: 'Failed to save target',
    confirm_delete_target: 'Are you sure you want to delete this target?',
    target_deleted: 'Target deleted successfully',
    target_delete_failed: 'Failed to delete target',
    label_used: 'Used',
    label_limit: 'Limit',
    label_collected: 'Collected',
    label_target: 'Target',
    label_time_left: 'Time Left',
    label_until: 'until',
    delete_income: 'Delete Income',
    delete_expense: 'Delete Expense',
    security_password_prompt: 'For security reasons, enter your account password to confirm data deletion.',
    account_password: 'Account Password',
    confirm_delete: 'Confirm Delete',
    income_added_success: 'Income added successfully!',
    income_added_failed: 'Failed to add income',
    income_deleted_success: 'Income deleted successfully',
    income_deleted_failed: 'Failed to delete income',
    expense_added_success: 'Expense added successfully!',
    expense_added_failed: 'Failed to record expense',
    expense_deleted_success: 'Expense deleted successfully',
    expense_deleted_failed: 'Failed to delete expense',
    failed_load_data: 'Failed to load data',
    receipt_photo_optional: 'Receipt/Memory Photo (Optional)',
    fill_report_form: 'Please fill in the report subject and message',
    report_sent_success: 'Report sent to Admin successfully',
    report_sent_failed: 'Failed to send report',
    notifications_cleared: 'Notifications cleared',
    notifications_clear_failed: 'Failed to clear notifications',
    logout_success: 'Logged out successfully',
    uploading_photo: 'Uploading photo...',
    photo_uploaded_success: 'Profile photo updated successfully',
    photo_upload_failed: 'Failed to upload profile photo',
    confirm_clear_notifs: 'Clear all notifications?',
    clear_all: 'Clear All',
    no_notifications: 'No notifications yet',
    notifications: 'Notifications',
    admin_load_failed: 'Failed to load admin data',
    account_activated: 'Account activated successfully',
    account_suspended: 'Account suspended successfully',
    status_update_failed: 'Failed to update account status',
    account_deleted: 'Account deleted successfully',
    account_delete_failed: 'Failed to delete account',
    receipt_load_failed: 'Failed to load user receipts',
    reply_empty: 'Reply text is empty',
    reply_sent: 'Reply sent',
    reply_failed: 'Failed to send reply',
    report_deleted: 'Report deleted successfully',
    report_delete_failed: 'Failed to delete report',
    delete_account_confirm: 'Are you sure you want to permanently delete this account and all its transactions?',
    delete_report_confirm: 'Are you sure you want to delete this report?',
    account_suspended_title: 'Account Suspended',
    account_suspended_desc: 'Your account has been locked by the administrator due to a violation or security reasons. You cannot perform any activities within the application.',
    report_to_admin: 'Report to Admin',
    delete_profile_picture: 'Delete Profile Picture',
    delete_receipt_photo: 'Delete Receipt Photo',
    profile_picture_deleted: 'Profile picture deleted successfully',
    profile_picture_delete_failed: 'Failed to delete profile picture',
    receipt_photo_deleted: 'Receipt photo deleted successfully',
    receipt_photo_delete_failed: 'Failed to delete receipt photo',
    confirm_delete_profile_picture: 'Are you sure you want to delete this user\'s profile picture because it is inappropriate?',
    confirm_delete_receipt_photo: 'Are you sure you want to delete this receipt photo because it is inappropriate?',
    receipt: 'Receipt',
    currency: 'Currency',
    new_expense_recorded: 'New expense recorded',
    new_income_recorded: 'New income added',
  },
  ja: {
    dashboard: 'ダッシュボード',
    income: '収入',
    expense: '支出',
    contact: '連絡先',
    daily_journal: 'デイリー帳',
    total_income: '総収益',
    total_expense: '総支出',
    net_profit: '純利益',
    gross_profit: '粗利益',
    financial_report: 'レポート',
    finance: '財務',
    welcome_tagline: 'AllFinanceへようこそ。スマートな財務管理プラットフォームで資産を監視・管理しましょう。',
    all_totals: '全合計',
    income_ytd: '収益 (YTD)',
    expense_ytd: '支出 (YTD)',
    revenue_expense_12m: '営業収益と支出（過去12ヶ月）',
    revenue: '収益',
    operating_margin: '営業利益率',
    gross_profit_12m: '過去12ヶ月の粗利益',
    gross_profit_line: '粗利益',
    gross_margin: '粗利益率',
    income_expense_comparison: '収入と支出の比較',
    expense_by_category: 'カテゴリ別支出',
    loading_dashboard: 'ダッシュボード読込中...',
    ai_help: 'AIサポート',
    logout: 'ログアウト',
    food: '食料',
    beauty: '美容',
    culture: '文化',
    health: '健康',
    gift: 'ギフト',
    transportation: '交通',
    education: '教育',
    household: '家事',
    apparel: '衣料',
    monthly_income: '今月の総収入',
    monthly_expense: '今月の総支出',
    net_balance: '純残高',
    journal_subtitle: '日次財務取引のサマリー',
    calendar_prev: '前月',
    calendar_next: '翌月',
    income_subtitle: '収入源の追跡と管理',
    add_income: '収入を追加',
    total_transactions: '総取引数',
    search_income: '🔍 収入を検索...',
    transaction_date: '取引日',
    category: 'カテゴリー',
    description: '説明',
    amount: '金額',
    no_income_data: 'まだ収入データはありません',
    expense_subtitle: '支出の追跡と管理',
    add_expense: '支出を追加',
    search_expense: '🔍 支出を検索...',
    no_expense_data: 'まだ支出データはありません',
    contact_subtitle: '連絡先とビジネスパートナーの管理',
    add_contact: '連絡先を追加',
    total_contacts: '総連絡先',
    search_contact: '🔍 連絡先を検索...',
    contact_name: '連絡先名',
    contact_info: '連絡先情報',
    address: '住所',
    no_contact_data: 'まだ連絡先はありません',
    actions: 'アクション',
    month_word: '月',
    surplus: '余剰',
    deficit: '赤字',
    selected: '選択済',
    today_balance: '本日の残高',
    no_transactions_today: '本日は取引がありません',
    select_date: '日付を選択',
    click_date_hint: 'カレンダーの日付をクリックして、毎日の取引の詳細を表示します',
    at_allfinance: 'AllFinanceにて',
    edit_profile: 'プロフィールを編集',
    select_category: 'カテゴリーを選択',
    eg_amount: '例 500.00',
    eg_desc_income: '例 商品Xを5つ販売',
    eg_desc_expense: '例 原材料を購入',
    cancel: 'キャンセル',
    financial_target_title: '財務目標',
    create_target: '目標を作成',
    expense_limit: '支出制限',
    income_savings_target: '収入・貯蓄目標',
    no_expense_target: 'まだ支出目標はありません。',
    no_income_target: 'まだ収入目標はありません。',
    target_name: '目標名',
    eg_target_name: '例：月々の食費 / 新しい靴',
    target_type: '目標タイプ',
    target_amount: '目標金額',
    period: '期間',
    '1_day': '1日',
    '3_days': '3日',
    '1_week': '1週間',
    '1_month': '1ヶ月',
    saving: '保存中...',
    save_target: '目標を保存',
    over_limit: '制限超過！',
    over_limit_desc: '支出が設定された目標制限に達したか超えました。この目標は削除されます。',
    ok: 'OK',
    congrats: 'おめでとうございます！ 🎉',
    target_achieved: '目標を無事に達成しました：',
    continue_btn: '続行',
    send_report: 'レポートを送信',
    report_subject: '件名',
    report_subject_placeholder: '例：バグ、新機能、またはヘルプ',
    report_message: 'レポートメッセージ',
    report_message_placeholder: '問題やレポートを詳細に説明してください...',
    sending: '送信中...',
    anti_spam_warning: 'スパム防止システムの警告：',
    anti_spam_rule_1: 'レポートのクオータの最大制限は3です。',
    anti_spam_rule_2: 'クオータが尽きた場合、2日間待つ必要があります。',
    anti_spam_rule_3: 'これに3回以上違反すると、アカウントは自動的に削除されます！',
    more_options: 'その他のオプション',
    feature_coming_soon: 'その他の機能は近日公開予定です',
    dashboard_name_updated: 'ダッシュボード名が正常に更新されました',
    dashboard_name_update_failed: 'ダッシュボード名の更新に失敗しました',
    failed_load_dashboard: 'ダッシュボードデータの読み込みに失敗しました',
    fill_target_form: '目標フォームに記入してください',
    target_saved: '目標が正常に保存されました',
    target_save_failed: '目標の保存に失敗しました',
    confirm_delete_target: 'この目標を削除してもよろしいですか？',
    target_deleted: '目標が正常に削除されました',
    target_delete_failed: '目標の削除に失敗しました',
    label_used: '使用済み',
    label_limit: '上限',
    label_collected: '積立済み',
    label_target: '目標',
    label_time_left: '残り時間',
    label_until: '〜',
    delete_income: '収入を削除',
    delete_expense: '支出を削除',
    security_password_prompt: 'セキュリティ上の理由から、データの削除を確認するためにアカウントのパスワードを入力してください。',
    account_password: 'アカウントのパスワード',
    confirm_delete: '削除を確認',
    income_added_success: '収入が正常に追加されました！',
    income_added_failed: '収入の追加に失敗しました',
    income_deleted_success: '収入が正常に削除されました',
    income_deleted_failed: '収入の削除に失敗しました',
    expense_added_success: '支出が正常に追加されました！',
    expense_added_failed: '支出の記録に失敗しました',
    expense_deleted_success: '支出が正常に削除されました',
    expense_deleted_failed: '支出の削除に失敗しました',
    failed_load_data: 'データの読み込みに失敗しました',
    receipt_photo_optional: '領収書/思い出の写真（任意）',
    fill_report_form: 'レポートの件名とメッセージを入力してください',
    report_sent_success: '管理者にレポートを送信しました',
    report_sent_failed: 'レポートの送信に失敗しました',
    notifications_cleared: '通知をクリアしました',
    notifications_clear_failed: '通知のクリアに失敗しました',
    logout_success: '正常にログアウトしました',
    uploading_photo: '写真をアップロード中...',
    photo_uploaded_success: 'プロフィール写真が正常に更新されました',
    photo_upload_failed: 'プロフィール写真のアップロードに失敗しました',
    confirm_clear_notifs: 'すべての通知をクリアしますか？',
    clear_all: 'すべてクリア',
    no_notifications: 'まだ通知はありません',
    notifications: '通知',
    admin_load_failed: '管理データの読み込みに失敗しました',
    account_activated: 'アカウントが正常に有効化されました',
    account_suspended: 'アカウントが正常に停止されました',
    status_update_failed: 'アカウントのステータスの更新に失敗しました',
    account_deleted: 'アカウントが正常に削除されました',
    account_delete_failed: 'アカウントの削除に失敗しました',
    receipt_load_failed: 'ユーザーの領収書の読み込みに失敗しました',
    reply_empty: '返信テキストが空です',
    reply_sent: '返信を送信しました',
    reply_failed: '返信の送信に失敗しました',
    report_deleted: 'レポートが正常に削除されました',
    report_delete_failed: 'レポートの削除に失敗しました',
    delete_account_confirm: 'このアカウントとすべてのトランザクションを完全に削除してもよろしいですか？',
    delete_report_confirm: 'このレポートを削除してもよろしいですか？',
    account_suspended_title: 'アカウントが停止されました',
    account_suspended_desc: '違反またはセキュリティ上の理由により、管理者によってアカウントがロックされました。アプリケーション内でいかなるアクティビティも実行できません。',
    report_to_admin: '管理者に報告',
    delete_profile_picture: 'プロフィール写真を削除',
    delete_receipt_photo: '領収書の写真を削除',
    profile_picture_deleted: 'プロフィール写真が正常に削除されました',
    profile_picture_delete_failed: 'プロフィール写真の削除に失敗しました',
    receipt_photo_deleted: '領収書の写真が正常に削除されました',
    receipt_photo_delete_failed: '領収書の写真の削除に失敗しました',
    confirm_delete_profile_picture: '不適切であるため、このユーザーのプロフィール写真を削除してもよろしいですか？',
    confirm_delete_receipt_photo: '不適切であるため、この領収書の写真を削除してもよろしいですか？',
    receipt: '領収書',
    currency: '通貨',
    new_expense_recorded: '新しい支出が記録されました',
    new_income_recorded: '新しい収入が追加されました',
  },
  ms: {
    dashboard: 'Papan Pemuka',
    income: 'Pendapatan',
    expense: 'Perbelanjaan',
    contact: 'Kenalan',
    daily_journal: 'Jurnal Harian',
    total_income: 'Jumlah Pendapatan',
    total_expense: 'Jumlah Perbelanjaan',
    net_profit: 'Keuntungan Bersih',
    gross_profit: 'Keuntungan Kasar',
    financial_report: 'Laporan',
    finance: 'Kewangan',
    welcome_tagline: 'Selamat datang ke AllFinance, platform pengurusan kewangan pintar anda. Pantau dan urus aset anda dengan lebih mudah.',
    all_totals: 'Semua Jumlah Kiraan',
    income_ytd: 'Pendapatan (YTD)',
    expense_ytd: 'Perbelanjaan (YTD)',
    revenue_expense_12m: 'Hasil Operasi dan Perbelanjaan (12 bulan lepas)',
    revenue: 'Hasil',
    operating_margin: 'Margin Operasi',
    gross_profit_12m: 'Keuntungan Kasar 12 Bulan Lepas',
    gross_profit_line: 'Keuntungan Kasar',
    gross_margin: 'Margin Kasar',
    income_expense_comparison: 'Perbandingan Pendapatan & Perbelanjaan',
    expense_by_category: 'Perbelanjaan mengikut Kategori',
    loading_dashboard: 'Memuatkan Papan Pemuka...',
    ai_help: 'Bantuan AI',
    logout: 'Log Keluar',
    food: 'Makanan',
    beauty: 'Kecantikan',
    culture: 'Budaya',
    health: 'Kesihatan',
    gift: 'Hadiah',
    transportation: 'Pengangkutan',
    education: 'Pendidikan',
    household: 'Isi Rumah',
    apparel: 'Pakaian',
    monthly_income: 'Jumlah Pendapatan Bulan Ini',
    monthly_expense: 'Jumlah Perbelanjaan Bulan Ini',
    net_balance: 'Baki Bersih',
    journal_subtitle: 'Ringkasan transaksi kewangan harian',
    calendar_prev: 'Bulan Lepas',
    calendar_next: 'Bulan Seterusnya',
    income_subtitle: 'Jejak dan urus sumber pendapatan anda',
    add_income: 'Tambah Pendapatan',
    total_transactions: 'Jumlah Transaksi',
    search_income: '🔍 Cari pendapatan...',
    transaction_date: 'Tarikh Transaksi',
    category: 'Kategori',
    description: 'Keterangan',
    amount: 'Jumlah',
    no_income_data: 'Tiada data pendapatan lagi',
    expense_subtitle: 'Jejak dan urus perbelanjaan anda',
    add_expense: 'Tambah Perbelanjaan',
    search_expense: '🔍 Cari perbelanjaan...',
    no_expense_data: 'Tiada data perbelanjaan lagi',
    contact_subtitle: 'Urus kenalan dan rakan kongsi perniagaan anda',
    add_contact: 'Tambah Kenalan',
    total_contacts: 'Jumlah Kenalan',
    search_contact: '🔍 Cari kenalan...',
    contact_name: 'Nama Kenalan',
    contact_info: 'Maklumat Kenalan',
    address: 'Alamat',
    no_contact_data: 'Tiada kenalan lagi',
    actions: 'Tindakan',
    month_word: 'Bulan',
    surplus: 'Lebihan',
    deficit: 'Defisit',
    selected: 'Dipilih',
    today_balance: 'Baki Hari Ini',
    no_transactions_today: 'Tiada transaksi hari ini',
    select_date: 'Pilih Tarikh',
    click_date_hint: 'Klik pada tarikh di kalendar untuk melihat butiran transaksi harian',
    at_allfinance: 'di AllFinance',
    edit_profile: 'Ubah Profil Saya',
    select_category: 'Pilih Kategori',
    eg_amount: 'cth. 500.00',
    eg_desc_income: 'cth. Menjual 5 unit Produk X',
    eg_desc_expense: 'cth. Membeli bahan mentah',
    cancel: 'Batal',
    financial_target_title: 'SASARAN KEWANGAN',
    create_target: 'Cipta Sasaran',
    expense_limit: 'Had Perbelanjaan',
    income_savings_target: 'Sasaran Pendapatan / Simpanan',
    no_expense_target: 'Belum ada sasaran perbelanjaan.',
    no_income_target: 'Belum ada sasaran pendapatan.',
    target_name: 'Nama Sasaran',
    eg_target_name: 'Contoh: Runcit Bulanan / Kasut Baru',
    target_type: 'Jenis Sasaran',
    target_amount: 'Jumlah Sasaran',
    period: 'Tempoh',
    '1_day': '1 Hari',
    '3_days': '3 Hari',
    '1_week': '1 Minggu',
    '1_month': '1 Bulan',
    saving: 'Menyimpan...',
    save_target: 'Simpan Sasaran',
    over_limit: 'Lebihan Had!',
    over_limit_desc: 'Perbelanjaan anda telah mencapai atau melebihi had sasaran. Sasaran ini akan dibuang.',
    ok: 'OK',
    congrats: 'Tahniah! 🎉',
    target_achieved: 'Anda telah berjaya mencapai sasaran',
    continue_btn: 'Teruskan',
    send_report: 'Hantar Laporan',
    report_subject: 'Subjek',
    report_subject_placeholder: 'Contoh: Pepijat, Ciri Baru, atau Bantuan',
    report_message: 'Mesej Laporan',
    report_message_placeholder: 'Terangkan isu atau laporan anda secara terperinci...',
    sending: 'Menghantar...',
    anti_spam_warning: 'Amaran Sistem Anti-Spam:',
    anti_spam_rule_1: 'Anda mempunyai had maksimum 3 kuota laporan.',
    anti_spam_rule_2: 'Jika kuota habis, anda mesti menunggu 2 hari.',
    anti_spam_rule_3: 'Jika melanggar lebih dari 3 kali, akaun akan dipadam secara automatik!',
    more_options: 'Pilihan Lain',
    feature_coming_soon: 'Ciri-ciri lain akan datang tidak lama lagi',
    dashboard_name_updated: 'Nama papan pemuka berjaya dikemas kini',
    dashboard_name_update_failed: 'Gagal mengemas kini nama papan pemuka',
    failed_load_dashboard: 'Gagal memuatkan data papan pemuka',
    fill_target_form: 'Sila lengkapkan borang sasaran',
    target_saved: 'Sasaran berjaya disimpan',
    target_save_failed: 'Gagal menyimpan sasaran',
    confirm_delete_target: 'Adakah anda pasti mahu memadam sasaran ini?',
    target_deleted: 'Sasaran berjaya dipadam',
    target_delete_failed: 'Gagal memadam sasaran',
    label_used: 'Digunakan',
    label_limit: 'Had',
    label_collected: 'Terkumpul',
    label_target: 'Sasaran',
    label_time_left: 'Masa Tinggal',
    label_until: 'hingga',
    delete_income: 'Padam Pendapatan',
    delete_expense: 'Padam Perbelanjaan',
    security_password_prompt: 'Atas sebab keselamatan, masukkan kata laluan akaun anda untuk mengesahkan pemadaman data ini.',
    account_password: 'Kata Laluan Akaun',
    confirm_delete: 'Sahkan Pemadaman',
    income_added_success: 'Pendapatan berjaya ditambah!',
    income_added_failed: 'Gagal menambah pendapatan',
    income_deleted_success: 'Pendapatan berjaya dipadam',
    income_deleted_failed: 'Gagal memadam pendapatan',
    expense_added_success: 'Perbelanjaan berjaya ditambah!',
    expense_added_failed: 'Gagal merekodkan perbelanjaan',
    expense_deleted_success: 'Perbelanjaan berjaya dipadam',
    expense_deleted_failed: 'Gagal memadam perbelanjaan',
    failed_load_data: 'Gagal memuatkan data',
    receipt_photo_optional: 'Foto Resit/Kenangan (Pilihan)',
    fill_report_form: 'Sila isi subjek dan mesej laporan',
    report_sent_success: 'Laporan berjaya dihantar ke Admin',
    report_sent_failed: 'Gagal menghantar laporan',
    notifications_cleared: 'Notifikasi dibersihkan',
    notifications_clear_failed: 'Gagal membersihkan notifikasi',
    logout_success: 'Berjaya log keluar',
    uploading_photo: 'Memuat naik foto...',
    photo_uploaded_success: 'Foto profil berjaya dikemas kini',
    photo_upload_failed: 'Gagal memuat naik foto profil',
    confirm_clear_notifs: 'Bersihkan semua notifikasi?',
    clear_all: 'Bersihkan Semua',
    no_notifications: 'Tiada notifikasi lagi',
    notifications: 'Notifikasi',
    admin_load_failed: 'Gagal memuatkan data admin',
    account_activated: 'Akaun berjaya diaktifkan',
    account_suspended: 'Akaun berjaya digantung',
    status_update_failed: 'Gagal mengemas kini status akaun',
    account_deleted: 'Akaun berjaya dipadam',
    account_delete_failed: 'Gagal memadam akaun',
    receipt_load_failed: 'Gagal memuatkan resit pengguna',
    reply_empty: 'Teks balasan kosong',
    reply_sent: 'Balasan dihantar',
    reply_failed: 'Gagal menghantar balasan',
    report_deleted: 'Laporan berjaya dipadam',
    report_delete_failed: 'Gagal memadam laporan',
    delete_account_confirm: 'Adakah anda pasti mahu memadam akaun ini secara kekal berserta semua transaksinya?',
    delete_report_confirm: 'Adakah anda pasti mahu memadam laporan ini?',
    account_suspended_title: 'Akaun Digantung',
    account_suspended_desc: 'Akaun anda telah dikunci oleh pentadbir kerana pelanggaran atau sebab keselamatan. Anda tidak boleh melakukan sebarang aktiviti dalam aplikasi.',
    report_to_admin: 'Lapor ke Admin',
    delete_profile_picture: 'Padam Foto Profil',
    delete_receipt_photo: 'Padam Foto Resit',
    profile_picture_deleted: 'Foto profil berjaya dipadam',
    profile_picture_delete_failed: 'Gagal memadam foto profil',
    receipt_photo_deleted: 'Foto resit berjaya dipadam',
    receipt_photo_delete_failed: 'Gagal memadam foto resit',
    confirm_delete_profile_picture: 'Adakah anda pasti mahu memadam foto profil pengguna ini kerana ia tidak sesuai?',
    confirm_delete_receipt_photo: 'Adakah anda pasti mahu memadam foto resit ini kerana ia tidak sesuai?',
    receipt: 'Resit',
    currency: 'Mata Wang',
    new_expense_recorded: 'Perbelanjaan baru dicatat',
    new_income_recorded: 'Pendapatan baru ditambah',
  },
};

interface CurrencyContextType {
  currentCurrency: Currency;
  setCurrentCurrency: (currency: Currency) => void;
  formatCurrency: (amount: number, compact?: boolean) => string;
  t: (key: TranslationKey) => string;
}

export const CurrencyContext = createContext<CurrencyContextType>({
  currentCurrency: currencies[0],
  setCurrentCurrency: () => {},
  formatCurrency: () => '',
  t: (key) => key,
});

export const CurrencyProvider = ({ children }: { children: ReactNode }) => {
  const { user, updateUser } = React.useContext(AuthContext);
  
  const storageKey = user ? `app_currency_${user.id}` : 'app_currency_guest';

  const [currentCurrency, setCurrentCurrencyState] = useState<Currency>(currencies[0]);

  React.useEffect(() => {
    if (user && user.currency) {
      const found = currencies.find(c => c.code === user.currency);
      if (found) {
        setCurrentCurrencyState(found);
        localStorage.setItem(storageKey, user.currency);
        return;
      }
    }

    const saved = localStorage.getItem(storageKey);
    if (saved) {
      const found = currencies.find(c => c.code === saved);
      if (found) setCurrentCurrencyState(found);
    } else {
      setCurrentCurrencyState(currencies[0]);
    }
  }, [storageKey, user]);

  const setCurrentCurrency = async (currency: Currency) => {
    setCurrentCurrencyState(currency);
    localStorage.setItem(storageKey, currency.code);
    if (user) {
      try {
        const response = await axiosInstance.put('/auth/profile', { currency: currency.code });
        if (response.data && response.data.user) {
          updateUser(response.data.user);
        }
      } catch (error) {
        console.error('Failed to save currency to profile', error);
      }
    }
  };

  const formatCurrency = (amount: number, compact: boolean = false) => {
    const options: Intl.NumberFormatOptions = {
      style: 'currency',
      currency: currentCurrency.code,
      minimumFractionDigits: compact ? 0 : (currentCurrency.code === 'IDR' || currentCurrency.code === 'JPY' ? 0 : 2),
      maximumFractionDigits: compact ? 1 : (currentCurrency.code === 'IDR' || currentCurrency.code === 'JPY' ? 0 : 2),
    };

    if (compact) {
      options.notation = 'compact';
      options.compactDisplay = 'short';
    }

    return new Intl.NumberFormat(currentCurrency.locale, options).format(amount);
  };

  const t = (key: TranslationKey): string => {
    const langTranslations = translations[currentCurrency.lang];
    return langTranslations[key] ?? key;
  };

  return (
    <CurrencyContext.Provider value={{ currentCurrency, setCurrentCurrency, formatCurrency, t }}>
      {children}
    </CurrencyContext.Provider>
  );
};
